'use client';
import React, { useState } from 'react';
import { useDesignTokens } from '@/hooks/useDesignTokens';
import { useTheme } from '@/contexts/ThemeContext';

const VocabularyList = () => {
  const designTokens = useDesignTokens();
  const { theme } = useTheme();
  const tokens = theme === 'light' ? designTokens.colors : designTokens.colors;
  const [selectedWord, setSelectedWord] = useState<string | null>(null);
  const [selectedCategory, setSelectedCategory] = useState<keyof typeof vocabulary | 'all'>('all');

  const categories = {
    academic: 'Akademik Terimler',
    science: 'Bilim ve Tıp',
    environment: 'Çevre ve Doğa',
    social: 'Sosyal Kavramlar',
    general: 'Genel Kelimeler',
    I00kelime: 'Videodaki 100 Kelime',
  };

  const vocabulary = {
    academic: [
      { en: 'methodology', tr: 'metodoloji' },
      { en: 'empirical', tr: 'deneysel' },
      { en: 'theoretical', tr: 'teorik' },
      { en: 'cognitive development', tr: 'bilişsel gelişim' },
      { en: 'research', tr: 'araştırma' },
      { en: 'comprehensive', tr: 'kapsamlı' },
      { en: 'analyze', tr: 'analiz etmek' },
      // Yeni eklenen kelimeler
      { en: 'intelligence', tr: 'zeka' },
      { en: 'disciplines', tr: 'disiplinler' },
      { en: 'identity', tr: 'kimlik' },
      { en: 'comprehensive', tr: 'kapsamlı' },
      { en: 'evidence', tr: 'kanıt' },
      { en: 'lesions', tr: 'lezyonlar' },
      { en: 'cognitive function', tr: 'bilişsel işlev' },
      { en: 'extensive', tr: 'kapsamlı' },
      { en: 'research', tr: 'araştırma' },
      { en: 'condition', tr: 'durum' },
      { en: 'cardiovascular', tr: 'kalp-damar' },
      { en: 'neurons', tr: 'sinir hücreleri' },
      { en: 'ecological awareness', tr: 'ekolojik farkındalık' },
      { en: 'fragility', tr: 'kırılganlık' },
      { en: 'evidence', tr: 'kanıt' },
      { en: 'intelligence', tr: 'zeka' },
      { en: 'comprehensive', tr: 'kapsamlı' },
      { en: 'severity', tr: 'şiddet' },
      { en: 'cognitive therapy', tr: 'bilişsel terapi' },
      { en: 'intervention', tr: 'müdahale' },
      { en: 'abnormal', tr: 'anormal' },
      { en: 'efficiency', tr: 'verimlilik' },
      { en: 'routines', tr: 'rutinler' },
      { en: 'conscious', tr: 'bilinçli' },
      { en: 'spatial', tr: 'uzamsal' },
      { en: 'coordination', tr: 'koordinasyon' },
      { en: 'chronic', tr: 'kronik' },
      { en: 'resistance', tr: 'direnç' },
      { en: 'pollination', tr: 'tozlaşma' },
      { en: 'extinction', tr: 'yok olma' },
      { en: 'habitat', tr: 'yaşam alanı' },
      { en: 'ecological', tr: 'ekolojik' },
      { en: 'biodiversity', tr: 'biyoçeşitlilik' },
      { en: 'conservation', tr: 'koruma' },
      { en: 'dominant', tr: 'baskın' },
      { en: 'impairment', tr: 'bozukluk' },
      { en: 'environmental diplomacy', tr: 'çevre diplomasisi' },
      { en: 'bilateral', tr: 'iki taraflı' },
      { en: 'multilateral', tr: 'çok taraflı' },
      { en: 'awareness', tr: 'farkındalık' },
      { en: 'boundaries', tr: 'sınırlar' },
      { en: 'consumption', tr: 'tüketim' },
      { en: 'pollution', tr: 'kirlilik' },
      { en: 'regulations', tr: 'düzenlemeler' },
      { en: 'treaties', tr: 'anlaşmalar' },
      { en: 'conventions', tr: 'sözleşmeler' },
      { en: 'cognitive development', tr: 'bilişsel gelişim' },
      { en: 'neuroimaging', tr: 'beyin görüntüleme' },
      { en: 'methodology', tr: 'metodoloji' },
      { en: 'influence', tr: 'etki' },
      { en: 'universality', tr: 'evrensellik' },
      { en: 'uniqueness', tr: 'benzersizlik' },
      { en: 'intelligence', tr: 'zeka' },
      { en: 'innate', tr: 'doğuştan' },
      { en: 'therapeutic', tr: 'tedavi edici' },
      { en: 'expansion', tr: 'genişleme' },
      { en: 'formulation', tr: 'formülasyon' },
      { en: 'improvement', tr: 'gelişme' },
      { en: 'impairments', tr: 'bozukluklar' },
      { en: 'severe', tr: 'şiddetli' },
      { en: 'magical', tr: 'sihirli' },
      { en: 'culinary', tr: 'mutfakla ilgili' },
      { en: 'proportion', tr: 'oran' },
      { en: 'precise', tr: 'kesin' },
      { en: 'starchy', tr: 'nişastalı' },
      { en: 'distinct', tr: 'belirgin' },
      { en: 'absorb', tr: 'emmek' },
      { en: 'texture', tr: 'doku' },
      { en: 'cuisine', tr: 'mutfak' },
      { en: 'benefit', tr: 'fayda' },
      { en: 'exhaustive', tr: 'kapsamlı' },
      { en: 'consumption', tr: 'tüketim' },
      { en: 'commodity', tr: 'mal' },
      { en: 'sophisticated', tr: 'karmaşık' },
      { en: 'neoclassical', tr: 'neoklasik' },
      { en: 'intertwined', tr: 'iç içe geçmiş' },
      { en: 'context', tr: 'bağlam' },
      { en: 'distribution', tr: 'dağıtım' },
      { en: 'remarkable', tr: 'dikkat çekici' },
      { en: 'specialised', tr: 'uzmanlaşmış' },
      { en: 'niche', tr: 'özel' },
      { en: 'vital', tr: 'hayati' },
      { en: 'illuminate', tr: 'aydınlatmak' },
      { en: 'bizarre', tr: 'tuhaf' },
      { en: 'origin', tr: 'köken' },
      { en: 'comprehensive', tr: 'kapsamlı' },
      { en: 'controversy', tr: 'tartışma' },
      { en: 'argument', tr: 'tartışma' },
      { en: 'uncertainty', tr: 'belirsizlik' },
      { en: 'ageing', tr: 'yaşlanma' },
      { en: 'blood flow', tr: 'kan akışı' },
      { en: 'mobility', tr: 'hareketlilik' },
      { en: 'alleviate', tr: 'hafifletmek' },
      { en: 'nutrients', tr: 'besin öğeleri' },
      { en: 'anti-inflammatory', tr: 'iltihap önleyici' },
      { en: 'rheumatoid arthritis', tr: 'romatoid artrit' },
      { en: 'neuroinflammation', tr: 'sinir iltihabı' },
      { en: 'progression', tr: 'ilerleme' },
      { en: 'tissue damage', tr: 'doku hasarı' },
      { en: 'obstruct', tr: 'engellemek' },
      { en: 'valued', tr: 'değer verilen' },
      { en: 'appreciate', tr: 'takdir etmek' },
      { en: 'sedentary', tr: 'hareketsiz' },
      { en: 'lifestyle', tr: 'yaşam tarzı' },
      { en: 'advances', tr: 'ilerlemeler' },
      { en: 'inevitable', tr: 'kaçınılmaz' },
      { en: 'induced', tr: 'neden olmuş' },
      { en: 'diving community', tr: 'dalış topluluğu' },
      { en: 'underwater', tr: 'su altı' },
      { en: 'worthwhile', tr: 'değerli' },
      { en: 'occurrence', tr: 'olay' },
      { en: 'participants', tr: 'katılımcıları' },
      { en: 'estimated', tr: 'tahmin edilen' },
      { en: 'thresholds', tr: 'eşikler' },
      { en: 'vast majority', tr: 'büyük çoğunluk' },
      { en: 'marine ecosystem', tr: 'deniz ekosistemi' },
      { en: 'disorder', tr: 'bozukluk' },
      { en: 'decode', tr: 'şifresini çözmek' },
      { en: 'spelling patterns', tr: 'yazım kalıpları' },
      { en: 'pronunciation', tr: 'telaffuz' },
      { en: 'variation', tr: 'çeşitlilik' },
      { en: 'prognosis', tr: 'hastalık seyri' },
      { en: 'remedial', tr: 'düzeltici' },
      { en: 'supportive', tr: 'destekleyici' },
      { en: 'evaluation', tr: 'değerlendirme' },
      { en: 'compensation', tr: 'telafi' },
      { en: 'manifest', tr: 'ortaya çıkmak' },
      { en: 'calcified', tr: 'kalsifiye olmuş' },
      { en: 'corpses', tr: 'cesetler' },
      { en: 'volcanic', tr: 'volkanik' },
      { en: 'cyanobacteria', tr: 'siyanobakteri' },
      { en: 'self-esteem', tr: 'özgüven' },
      { en: 'motivation', tr: 'motivasyon' },
      { en: 'learned helplessness', tr: 'öğrenilmiş çaresizlik' },
      { en: 'deficit', tr: 'eksiklik, açık' },
      { en: 'contemporary', tr: 'çağdaş' },
      { en: 'comprise', tr: 'içermek' },
      { en: 'attribute', tr: 'atfetmek' },
      { en: 'intact', tr: 'bozulmamış' },
      { en: 'implications', tr: 'sonuçlar' },
      { en: 'derive', tr: 'türemek' },
      { en: 'substantial', tr: 'önemli' },
      { en: 'persist', tr: 'devam etmek' },
      { en: 'implement', tr: 'uygulamak' },
      { en: 'inherent', tr: 'doğal, içkin' },
      { en: 'profound', tr: 'derin' },
      { en: 'subsequent', tr: 'sonraki' },
      { en: 'adjacent', tr: 'bitişik' },
      { en: 'preliminary', tr: 'ön' },
      { en: 'mandatory', tr: 'zorunlu' },
      { en: 'albeit', tr: 'her ne kadar' },
      { en: 'unprecedented', tr: 'benzeri görülmemiş' },
      { en: 'crucial', tr: 'çok önemli' },
      { en: 'respective', tr: 'ilgili' },
      { en: 'depicted', tr: 'tasvir edilmiş' },
      { en: 'feasible', tr: 'uygulanabilir' },
      { en: 'arbitrary', tr: 'keyfi' },
      { en: 'rigid', tr: 'katı' },
      { en: 'robust', tr: 'sağlam' },
      { en: 'empirical', tr: 'deneysel' },
      { en: 'provisional', tr: 'geçici' },
      { en: 'compatible', tr: 'uyumlu' },
      { en: 'contradictory', tr: 'çelişkili' },
      { en: 'criteria', tr: 'kriterler' },
      { en: 'supplement', tr: 'tamamlamak' },
      { en: 'magnitude', tr: 'büyüklük' },
      { en: 'inevitable', tr: 'kaçınılmaz' },
      { en: 'elaborate', tr: 'ayrıntılı' },
      { en: 'indigenous', tr: 'yerli' },
      { en: 'diverse', tr: 'çeşitli' },
      { en: 'approximately', tr: 'yaklaşık olarak' },
      { en: 'integrate', tr: 'bütünleştirmek' },
      { en: 'mutual', tr: 'karşılıklı' },
      { en: 'perspective', tr: 'bakış açısı' },
      { en: 'explicitly', tr: 'açıkça' },
      { en: 'implicit', tr: 'örtük' },
      { en: 'conceive', tr: 'tasarlamak' },
      { en: 'propagate', tr: 'yaymak' },
      { en: 'accumulate', tr: 'biriktirmek' },
      { en: 'constitute', tr: 'oluşturmak' }
    ],
    science: [
      { en: 'neuroimaging', tr: 'beyin görüntüleme' },
      { en: 'cardiovascular', tr: 'kalp-damar' },
      { en: 'cognitive function', tr: 'bilişsel işlev' },
      { en: 'lesions', tr: 'lezyonlar' },
      { en: 'neurons', tr: 'sinir hücreleri' },
      // Yeni eklenen kelimeler
      { en: 'neuroimaging', tr: 'beyin görüntüleme' },
      { en: 'artificial sweeteners', tr: 'yapay tatlandırıcılar' },
      { en: 'ageing', tr: 'yaşlanma' },
      { en: 'lesions', tr: 'lezyonlar' },
      { en: 'blood flow', tr: 'kan akışı' },
      { en: 'cognitive function', tr: 'bilişsel işlev' },
      { en: 'mobility', tr: 'hareketlilik' },
      { en: 'cardiovascular', tr: 'kalp-damar' },
      { en: 'nutrients', tr: 'besin öğeleri' },
      { en: 'anti-inflammatory', tr: 'iltihap önleyici' },
      { en: 'rheumatoid arthritis', tr: 'romatoid artrit' },
      { en: 'neuroinflammation', tr: 'sinir iltihabı' },
      { en: 'progression', tr: 'ilerleme' },
      { en: 'tissue damage', tr: 'doku hasarı' },
      { en: 'obstruct', tr: 'engellemek' },
      { en: 'neurons', tr: 'sinir hücreleri' }
    ],
    environment: [
      { en: 'sustainability', tr: 'sürdürülebilirlik' },
      { en: 'biodiversity', tr: 'biyoçeşitlilik' },
      { en: 'ecosystem', tr: 'ekosistem' },
      { en: 'conservation', tr: 'koruma' },
      { en: 'pollution', tr: 'kirlilik' },
      // Yeni eklenen kelimeler
      { en: 'sustainability', tr: 'sürdürülebilirlik' },
      { en: 'terrestrial', tr: 'karasal' },
      { en: 'retained', tr: 'korunan, saklanan' },
      { en: 'exceeded', tr: 'aşılmış' },
      { en: 'enhanced', tr: 'geliştirilmiş' },
      { en: 'mitigated', tr: 'hafifletilmiş' },
      { en: 'fulfilled', tr: 'yerine getirilmiş' },
      { en: 'predators', tr: 'yırtıcılar' },
      { en: 'pests', tr: 'zararlılar' },
      { en: 'eliminate', tr: 'ortadan kaldırmak' },
      { en: 'non-selective', tr: 'seçici olmayan' },
      { en: 'exploitation', tr: 'sömürü' },
      { en: 'disturbance', tr: 'rahatsızlık' },
      { en: 'catastrophe', tr: 'felaket' },
      { en: 'endangered', tr: 'nesli tükenmek üzere olan' },
      { en: 'retain', tr: 'korumak' },
      { en: 'deterioration', tr: ' kötüleşme' },
        { en: 'utilisation', tr: 'kullanım' } 
    ],
    social: [
      { en: 'cultural identity', tr: 'kültürel kimlik' },
      { en: 'diversity', tr: 'çeşitlilik' },
      { en: 'consumerism', tr: 'tüketicilik' },
      { en: 'individualism', tr: 'bireycilik' },
      { en: 'compliance', tr: 'uyum' },
      // Yeni eklenen kelimeler
      { en: 'commonality', tr: 'ortaklık, müştereklik' },
      { en: 'resolution', tr: 'karar, çözüm' },
      { en: 'exception', tr: 'istisna' },
      { en: 'alteration', tr: 'değişiklik' },
      { en: 'entitlement', tr: 'hak sahipliği' },
      { en: 'adherence', tr: 'bağlılık, uyum' },
      { en: 'moral standards', tr: 'ahlaki standartlar' },
      { en: 'workforce', tr: 'işgücü' },
      { en: 'inclinations', tr: 'eğilimler' },
      { en: 'oddities', tr: 'tuhaflıklar' },
      { en: 'incentives', tr: 'teşvikler' },
      { en: 'ramifications', tr: 'sonuçlar, etkiler' },
      { en: 'constraints', tr: 'kısıtlamalar' },
      { en: 'sociologists', tr: 'sosyologlar' },
      { en: 'ambiguous', tr: 'belirsiz, muğlak' },
      { en: 'overt', tr: 'açık, belirgin' },
      { en: 'intuitive', tr: 'sezgisel' },
      { en: 'abrupt', tr: 'ani' },
      { en: 'incessant', tr: 'sürekli, kesintisiz' },
      { en: 'undeniably', tr: 'inkâr edilemez şekilde' },
      { en: 'invariably', tr: 'değişmez şekilde' },
      { en: 'unevenly', tr: 'eşit olmayan şekilde' },
      { en: 'irreversibly', tr: 'geri döndürülemez şekilde' },
      { en: 'inseparably', tr: 'ayrılmaz şekilde' },
      { en: 'secure', tr: 'güvenli' },
      { en: 'knowledgeable', tr: 'bilgili' },
      { en: 'adjust', tr: 'uyarlamak' },
      { en: 'align with', tr: 'uyumlu olmak' },
      { en: 'bargain for', tr: 'pazarlık etmek' },
      { en: 'interfere with', tr: 'müdahale etmek' },
      { en: 'descend from', tr: 'inmek, türemek' },
      { en: 'assume', tr: 'varsaymak' },
      { en: 'linked', tr: 'bağlantılı' },
      { en: 'enlightenment', tr: 'aydınlanma' },
      { en: 'dissipated', tr: 'dağılmış' },
      { en: 'illuminate', tr: 'aydınlatmak' },
      { en: 'superstition', tr: 'batıl inanç' },
      { en: 'ignorance', tr: 'cehalet' },
      { en: 'explosive growth', tr: 'patlayıcı büyüme' },
      { en: 'impact', tr: 'etki' },
      { en: 'urge', tr: 'teşvik etmek' },
      { en: 'rebellion', tr: 'isyan' },
      { en: 'abolished', tr: 'kaldırılmış' },
      { en: 'devastating', tr: 'yıkıcı' },
      { en: 'manoeuvres', tr: 'manevralar' },
      { en: 'impose', tr: 'dayatmak' },
      { en: 'implement', tr: 'uygulamak' },
      { en: 'heritage', tr: 'miras' },
      { en: 'paradise', tr: 'cennet' },
      { en: 'archaeological', tr: 'arkeolojik' },
      { en: 'ancient', tr: 'antik, eski' },
      { en: 'sacred', tr: 'kutsal' },
      { en: 'norms', tr: 'kurallar' },
      { en: 'essential', tr: 'temel, önemli' },
      { en: 'diverge', tr: 'farklılaşmak' },
      { en: 'prevailing', tr: 'yaygın' },
      { en: 'uprising', tr: 'ayaklanma' },
      { en: 'clergy', tr: 'din adamları' },
      { en: 'grievances', tr: 'şikayetler' },
      { en: 'oppressed', tr: 'baskı altında' },
      { en: 'spectrum', tr: 'yelpaze' },
      { en: 'maladaptive', tr: 'uyumsuz' },
      { en: 'outpatient', tr: 'ayakta tedavi' },
      { en: 'impair', tr: 'bozmak, zayıflatmak' },
      { en: 'obstructive', tr: 'engelleyici' }
    ],
    general: [
      { en: 'profound', tr: 'derin, kapsamlı' },
      { en: 'albeit', tr: 'her ne kadar' },
      { en: 'crucial', tr: 'çok önemli' },
      { en: 'arbitrary', tr: 'keyfi' },
      { en: 'feasible', tr: 'uygulanabilir' },
      { en: 'honeybees', tr: 'bal arıları' },
      { en: 'forage', tr: 'yiyecek aramak' },
      { en: 'internal clock', tr: 'iç saat' },
      { en: 'indication', tr: 'gösterge' },
      { en: 'documentary', tr: 'belgesel' },
      { en: 'magnetic field', tr: 'manyetik alan' }

    ],

    I00kelime: [      { en: 'abandon', tr: 'terketmek, vazgeçmek' },
      { en: 'accept', tr: 'kabul etmek' },
      { en: 'access', tr: 'erişmek, ulaşmak' },
      { en: 'accomplish', tr: 'başarmak' },
      { en: 'adapt', tr: 'uyarlamak, uydurmak' },
      { en: 'adequately', tr: 'yeterli bir şekilde' },
      { en: 'admire', tr: 'hayran olmak' },
      { en: 'amazing', tr: 'şaşırtıcı' },
      { en: 'anticipate', tr: 'beklemek' },
      { en: 'appreciate', tr: 'takdir etmek, değerini bilmek' },
      { en: 'arrange', tr: 'düzenlemek, ayarlamak' },
      { en: 'assess', tr: 'değerlendirmek' },
      { en: 'assume', tr: 'varsaymak, farzetmek' },
      { en: 'attain', tr: 'elde etmek, erişmek' },
      { en: 'available', tr: 'mevcut, var olan' },
      { en: 'barely', tr: 'neredeyse yok gibi' },
      { en: 'common', tr: 'genel, bilindik' },
      { en: 'cancel', tr: 'iptal etmek' },
      { en: 'capture', tr: 'yakalamak, ele geçirmek' },
      { en: 'caution', tr: 'uyarı, dikkat' },
      { en: 'circulate', tr: 'dolaşmak, dolaştırmak' },
      { en: 'clarify', tr: 'açıklık getirmek' },
      { en: 'collapse', tr: 'devrilmek, çökmek' },
      { en: 'colleague', tr: 'iş arkadaşı' },
      { en: 'compel', tr: 'zorlamak, mecbur bırakmak' },
      { en: 'compete', tr: 'rekabet etmek, yarışmak' },
      { en: 'complain', tr: 'şikayet etmek' },
      { en: 'completely', tr: 'tamamen, bütünüyle' },
      { en: 'comprise', tr: 'içermek, oluşmak' },
      { en: 'conclude', tr: 'sonuç çıkarmak' },
      { en: 'conduct', tr: 'icra etmek, yerine getirmek' },
      { en: 'confess', tr: 'itiraf etmek' },
      { en: 'confident', tr: 'emin, özgüvenli' },
      { en: 'confirm', tr: 'onaylamak, doğrulamak' },
      { en: 'conflict', tr: 'çatışma, anlaşmazlık' },
      { en: 'consent', tr: 'rıza, izin' },
      { en: 'consequence', tr: 'sonuç, netice' },
      { en: 'consist of', tr: '-den ibaret olmak' },
      { en: 'constantly', tr: 'sürekli, aralıksız' },
      { en: 'consult', tr: 'danışmak' },
      { en: 'consume', tr: 'tüketmek' },
      { en: 'contribute', tr: 'katkıda bulunmak' },
      { en: 'controversial', tr: 'tartışmalı' },
      { en: 'conventional', tr: 'geleneksel' },
      { en: 'convince', tr: 'ikna etmek, inandırmak' },
      { en: 'deceive', tr: 'kandırmak, aldatmak' },
      { en: 'declare', tr: 'ilan etmek, beyan etmek' },
      { en: 'dedicate', tr: 'adamak' },
      { en: 'define', tr: 'tanımlamak' },
      { en: 'delay', tr: 'geciktirmek' },
      { en: 'demand', tr: 'talep, istek' },
      { en: 'demonstrate', tr: 'göstermek, protesto etmek' },
      { en: 'deny', tr: 'inkar etmek, yasaklamak' },
      { en: 'derive from', tr: '-den gelmek, türemek' },
      { en: 'deserve', tr: 'hak etmek' },
      { en: 'desire', tr: 'istek, arzu' },
      { en: 'destroy', tr: 'yıkmak, yok etmek' },
      { en: 'deteriorate', tr: 'kötüleşmek, kötüye gitmek' },
      { en: 'determination', tr: 'kararlılık' },
      { en: 'develop', tr: 'geliştirmek, genişletmek' },
      { en: 'diminish', tr: 'azalmak' },
      { en: 'discover', tr: 'keşfetmek' },
      { en: 'discuss', tr: 'tartışmak, görüşmek' },
      { en: 'disorder', tr: 'bozukluk, düzensizlik' },
      { en: 'display', tr: 'sergilemek, göstermek' },
      { en: 'distinguish', tr: 'ayırt etmek' },
      { en: 'enable', tr: 'olanaklı kılmak' },
      { en: 'evaluate', tr: 'değerlendirmek' },
      { en: 'essentially', tr: 'esas olarak' },
      { en: 'excessive', tr: 'aşırı, abartılı' },
      { en: 'exclusively', tr: 'yalnızca, sadece' },
      { en: 'facilitate', tr: 'kolaylaştırmak' },
      { en: 'gradually', tr: 'yavaş yavaş, kademeli olarak' },
      { en: 'illustrate', tr: 'örneklemek, açıklamak' },
      { en: 'impose', tr: 'zorla kabul ettirmek' },
      { en: 'improve', tr: 'geliştirmek' },
      { en: 'include', tr: 'dahil etmek, içermek' },
      { en: 'influence', tr: 'etki, etkilemek' },
      { en: 'maintain', tr: 'korumak, muhafaza etmek' },
      { en: 'necessity', tr: 'zorunluluk, mecburiyet' },
      { en: 'observe', tr: 'gözlemlemek' },
      { en: 'opportunity', tr: 'fırsat' },
      { en: 'particularly', tr: 'özellikle' },
      { en: 'preceding', tr: 'önce gelen, öncülük eden' },
      { en: 'precisely', tr: 'tam olarak, düzgün bir şekilde' },
      { en: 'require', tr: 'gerektirmek' }]
  
  
  
  };

  return (
    <div className="p-4 max-w-6xl mx-auto" style={{ backgroundColor: tokens.background.primary }}>
      <h1 className="text-3xl font-bold text-center mb-6" style={{ color: tokens.text.primary }}>
        YDS Kelime Listesi
      </h1>

      <div className="mb-6 flex flex-wrap gap-2 justify-center">
        <button
          onClick={() => setSelectedCategory('all')}
          className={`px-4 py-2 rounded transition-colors duration-300`}
          style={{
            backgroundColor: selectedCategory === 'all' ? designTokens.colors.primary[600] : tokens.background.secondary,
            color: tokens.text.primary,
          }}
        >
          Tümü
        </button>
        {Object.entries(categories).map(([key, value]) => (
          <button
            key={key}
            onClick={() => setSelectedCategory(key as keyof typeof vocabulary | 'all')}
            className={`px-4 py-2 rounded transition-colors duration-300`}
            style={{
              backgroundColor: selectedCategory === key ? designTokens.colors.primary[600] : tokens.background.secondary,
              color: tokens.text.primary,
            }}
          >
            {value}
          </button>
        ))}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {(selectedCategory === 'all'
          ? Object.values(vocabulary).flat()
          : vocabulary[selectedCategory as keyof typeof vocabulary]
        ).map((word, index) => (
          <div
            key={index}
            onClick={() => setSelectedWord(selectedWord === word.en ? null : word.en)}
            className="p-4 rounded-lg cursor-pointer transition-colors duration-300"
            style={{
              backgroundColor: tokens.background.secondary,
              borderLeft: selectedWord === word.en ? `4px solid ${designTokens.colors.primary[600]}` : `4px solid ${tokens.border.light}`,
            }}
          >
            <div style={{ color: tokens.text.primary }} className="font-semibold">
              {word.en}
            </div>
            {selectedWord === word.en && (
              <div style={{ color: tokens.text.secondary }} className="mt-2">
                {word.tr}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};

export default VocabularyList;